"""
Sovereign AI Workbench — API Routes

All endpoint definitions for the workbench API.
Routes are wired to real backend components where available.

Phase 4: Added streaming chat, model management endpoints, and live inference metrics.
Phase 6: Added /classify endpoint for routing preview without inference.
Phase 7: Added /code/generate endpoint for structured code generation.
"""

import json
import uuid
import time
import logging
from typing import Optional

from fastapi import APIRouter, File, HTTPException, UploadFile, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from backend.api.schemas import (
    ChatRequest,
    ChatResponse,
    ClassifyRequest,
    ClassifyResponse,
    ClassificationSignalSchema,
    CodeBlockSchema,
    CodeExecutionRequest,
    CodeExecutionResponse,
    CodeGenerateRequest,
    CodeGenerateResponse,
    GenerateRequest,
    GenerateResponse,
    ModelStatus,
    RouteInfo,
    RoutingDecisionSchema,
    SearchRequest,
    SearchResponse,
    SystemStatus,
    TaskType,
    ModelName,
    UploadResponse,
    VisionAnalyzeRequest,
    VisionAnalyzeResponse,
)
from backend.models.registry import get_all_models
from backend.router.task_classifier import task_classifier
from backend.router.router import model_router
from backend.router.ollama_client import ollama_client
from backend.router.coding import extract_code_blocks
from backend.api.health import probe_all
from backend.settings import settings
from backend.security.dependencies import require_permission, get_current_user

logger = logging.getLogger("sovereign.api.routes")

router = APIRouter()


# ── Chat / Query ───────────────────────────────────────────────────────────────


@router.post("/chat", response_model=ChatResponse, dependencies=[Depends(require_permission("ai.chat"))])
async def chat(request: ChatRequest):
    """
    Main chat endpoint. Classifies the task, routes to the appropriate model,
    executes tools as needed, and returns a response with sources.
    """
    start = time.time()
    request_id = str(uuid.uuid4())
    session_id = request.session_id or request_id

    # Use the real task classifier
    classification = task_classifier.classify(
        request.message,
        has_image=bool(request.images),
    )

    # Override with explicit request if provided
    task_type = request.task_type or classification.task_type
    model = request.model or classification.model

    # Attempt real model inference via the router
    try:
        result = await model_router.route(
            user_input=request.message,
            images=request.images,
            force_model=request.model,
            session_id=session_id,
        )
        response_text = result.get("response", "[No response from model]")
    except Exception as e:
        logger.warning("Model inference failed (expected if Ollama not running): %s", e)
        response_text = (
            f"[Sovereign AI] Task classified as '{task_type.value}' -> "
            f"model '{model.value}'. Inference backend not available: {e}"
        )

    duration = round((time.time() - start) * 1000, 2)

    return ChatResponse(
        response=response_text,
        route=RouteInfo(
            task_type=task_type,
            model=model,
            reason=classification.reason,
        ),
        sources=[],
        tools_used=[],
        files_created=[],
        sovereign=True,
        request_id=request_id,
        duration_ms=duration,
    )


@router.post("/chat/stream", dependencies=[Depends(require_permission("ai.chat"))])
async def chat_stream(request: ChatRequest):
    """
    Streaming chat endpoint. Returns Server-Sent Events (SSE) as tokens
    are generated by the model.

    Each event:
        data: {"chunk": "token text", "done": false}
        ...
        data: {"chunk": "", "done": true, "classification": {...}, "metrics": {...}}
    """
    session_id = request.session_id or str(uuid.uuid4())

    async def event_generator():
        try:
            async for chunk_data in model_router.route_stream(
                user_input=request.message,
                images=request.images,
                force_model=request.model,
                session_id=session_id,
            ):
                yield f"data: {json.dumps(chunk_data)}\n\n"
        except Exception as e:
            logger.error("Stream error: %s", e)
            error_event = {
                "chunk": f"[Error: {e}]",
                "done": True,
                "error": str(e),
            }
            yield f"data: {json.dumps(error_event)}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Sovereign": "true",
        },
    )


# ── Classification (Phase 6) ───────────────────────────────────────────────────


@router.post("/classify", response_model=ClassifyResponse, dependencies=[Depends(require_permission("ai.chat"))])
async def classify_input(request: ClassifyRequest):
    """
    Classify a user input and return the routing decision WITHOUT running
    model inference. Shows which model would be selected and why.

    This is the Dynamic Expertise Broker made visible — the frontend can
    display "This would be routed to Qwen2.5-Coder-7B because..." before
    the user commits to running the full inference.
    """
    try:
        decision = await model_router.classify_only(
            user_input=request.message,
            has_image=request.has_image,
            use_llm=request.use_llm,
        )
    except Exception as e:
        logger.error("Classification failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Classification error: {e}")

    # Build response with optional pattern explanation
    explanation = task_classifier.explain(request.message)

    # Convert signals to schema types
    kw_signal = None
    if decision.keyword_signal:
        kw_signal = ClassificationSignalSchema(
            source=decision.keyword_signal.source,
            task_type=decision.keyword_signal.task_type,
            model=decision.keyword_signal.model,
            confidence=decision.keyword_signal.confidence,
            reason=decision.keyword_signal.reason,
            duration_ms=decision.keyword_signal.duration_ms,
        )

    llm_signal = None
    if decision.llm_signal:
        llm_signal = ClassificationSignalSchema(
            source=decision.llm_signal.source,
            task_type=decision.llm_signal.task_type,
            model=decision.llm_signal.model,
            confidence=decision.llm_signal.confidence,
            reason=decision.llm_signal.reason,
            duration_ms=decision.llm_signal.duration_ms,
        )

    return ClassifyResponse(
        routing_decision=RoutingDecisionSchema(
            task_type=decision.task_type,
            model_category=decision.model_category,
            model_name=decision.model_name,
            confidence=decision.confidence,
            reason=decision.reason,
            used_llm=decision.used_llm,
            total_classification_ms=decision.total_classification_ms,
            keyword_signal=kw_signal,
            llm_signal=llm_signal,
            policy={
                "llm_threshold": decision.policy_llm_threshold,
                "prefer_llm": decision.policy_prefer_llm,
            },
        ),
        explanation=explanation,
    )


# ── Code Generation (Phase 7) ─────────────────────────────────────────────────


@router.post("/code/generate", response_model=CodeGenerateResponse, dependencies=[Depends(require_permission("agent.execute_code"))])
async def generate_code(request: CodeGenerateRequest):
    """
    Generate code using the specialized coder model (Qwen2.5-Coder-7B).

    Returns structured code blocks extracted from the model response,
    plus the raw response and routing metadata. This is the precursor
    to the Phase 10 sandbox integration where generated code will be
    executed in a Docker container.

    Flow:
        Prompt → Coder Model → Raw Response → Code Block Extraction → Structured Output
    """
    start = time.time()

    try:
        result = await model_router.generate_code(
            prompt=request.prompt,
            language=request.language,
            context=request.context,
            temperature=request.temperature,
            max_tokens=request.max_tokens,
        )
    except Exception as e:
        logger.error("Code generation failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Code generation error: {e}")

    duration_ms = round((time.time() - start) * 1000, 2)

    return CodeGenerateResponse(
        code_blocks=[
            CodeBlockSchema(
                language=b.language,
                code=b.code,
                description=b.description,
                line_count=b.line_count,
            )
            for b in result.code_blocks
        ],
        raw_response=result.raw_response,
        route=RouteInfo(
            task_type=TaskType.CODING,
            model=ModelName.QWEN25_CODER_7B,
            reason="Forced to coder model for code generation",
        ),
        model_used=result.model_used,
        duration_ms=duration_ms,
        total_lines=result.total_lines,
    )



# ── Vision Endpoints (Phase 8) ────────────────────────────────────────────────

@router.post("/vision/analyze", response_model=VisionAnalyzeResponse, dependencies=[Depends(require_permission("ai.vision"))])
async def analyze_vision(request: VisionAnalyzeRequest):
    """
    Dedicated endpoint for vision analysis.
    Forces the vision model and specialized system prompt.
    """
    try:
        result = await model_router.analyze_vision(
            prompt=request.prompt,
            images=request.images,
            temperature=request.temperature,
            max_tokens=request.max_tokens,
        )

        if not result.success:
            raise HTTPException(status_code=500, detail=result.error)

        return VisionAnalyzeResponse(
            content=result.content,
            route={
                "task_type": "vision",
                "model_category": "vision",
                "model_name": result.model_used,
            },
            model_used=result.model_used,
            duration_ms=result.duration_ms,
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ── Document Upload ────────────────────────────────────────────────────────────


@router.post("/upload", response_model=UploadResponse, dependencies=[Depends(require_permission("document.upload"))])
async def upload_document(
    file: UploadFile = File(...),
    department: Optional[str] = None,
    access_level: str = "engineering",
    description: Optional[str] = None,
):
    """
    Upload a document for processing. The pipeline will:
    1. Detect document type
    2. Run Docling for layout extraction (or fallback)
    3. Run PaddleOCR for scanned pages (Phase 13+)
    4. Chunk and embed
    5. Store in Qdrant with metadata
    """
    from backend.documents.ingest import ingestion_pipeline
    import shutil
    import os
    from pathlib import Path
    
    start = time.time()
    
    # Save uploaded file to temp/uploads directory
    upload_dir = Path("data/uploads")
    upload_dir.mkdir(parents=True, exist_ok=True)
    
    safe_filename = file.filename or "unknown.pdf"
    file_path = upload_dir / f"{uuid.uuid4().hex[:8]}_{safe_filename}"
    
    try:
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
            
        result = await ingestion_pipeline.ingest(
            file_path=str(file_path),
            department=department or "engineering",
            access_level=access_level,
            description=description,
        )
        
        # Cleanup uploaded file for zero-egress/ephemeral policy
        if file_path.exists():
            file_path.unlink()
            
    except Exception as e:
        logger.error("Upload failed: %s", e)
        raise HTTPException(status_code=500, detail=str(e))

    return UploadResponse(
        document_id=result.document_id,
        filename=result.filename,
        pages=result.pages,
        chunks=result.chunks,
        status=result.status,
        processing_time_ms=result.processing_time_ms,
    )


# ── RAG Search ─────────────────────────────────────────────────────────────────


@router.post("/search", response_model=SearchResponse, dependencies=[Depends(require_permission("rag.search"))])
async def search_documents(request: SearchRequest):
    """
    Hybrid search: dense (Qdrant) + BM25 -> merge -> rerank -> top K.
    RBAC filtering is applied BEFORE retrieval.
    """
    from backend.rag.embedder import embedding_service
    from backend.rag.retriever import hybrid_retriever
    from backend.rag.reranker import reranker_service
    from backend.api.schemas import SourceDocument
    from backend.rag.exceptions import RetrievalServiceError

    try:
        # 1. Embed query
        query_embedding = await embedding_service.embed_text(request.query)
    
        # 2. Hybrid search with RBAC
        candidates = await hybrid_retriever.search(
            query=request.query,
            query_embedding=query_embedding,
            top_k=request.top_k * 2 if request.rerank else request.top_k,
            user_role=request.user_role.value if hasattr(request.user_role, 'value') else request.user_role,
            department_filter=request.department_filter,
        )
    
        # 3. Rerank
        if request.rerank and candidates:
            candidates = await reranker_service.rerank(
                query=request.query,
                documents=candidates,
                top_k=request.top_k,
            )
    except RetrievalServiceError as e:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(e)
        )
        
    # 4. Format response
    source_docs = []
    for doc in candidates:
        source_docs.append(
            SourceDocument(
                document_id=doc.get("document_id", "unknown"),
                title=doc.get("filename") or doc.get("title") or "Document",
                page=doc.get("page"),
                relevance_score=doc.get("_rerank_score") if request.rerank else doc.get("_rrf_score", 0.0),
                snippet=doc.get("text", "")[:500] + "...",
            )
        )

    return SearchResponse(
        results=source_docs,
        query=request.query,
        total_found=len(source_docs),
        reranked=request.rerank,
    )


# ── Document Generation ───────────────────────────────────────────────────────
from backend.generators.service import deliverable_service
import os


@router.post("/generate", response_model=GenerateResponse, dependencies=[Depends(require_permission("report.create"))])
async def generate_document(request: GenerateRequest):
    """
    Generate enterprise documents (DOCX, XLSX, PPTX) from AI analysis.
    """
    output_format = request.output_format.lower()
    title = request.source_data.get("title", f"Generated_{request.request_type}")
    
    filepath = ""
    error = ""
    if output_format == "docx":
        filepath, error = await deliverable_service.create_and_validate_docx(
            title=title, content=request.source_data, template=request.template
        )
    elif output_format == "xlsx":
        filepath, error = await deliverable_service.create_and_validate_xlsx(
            title=title,
            data=request.source_data.get("data", []),
            summary=request.source_data.get("summary")
        )
    elif output_format == "pptx":
        filepath, error = await deliverable_service.create_and_validate_pptx(
            title=title,
            slides=request.source_data.get("slides", [])
        )
    elif output_format == "zip":
        filepath, error = await deliverable_service.create_and_validate_code_package(
            title=title,
            files=request.source_data.get("files", {})
        )
        
    if error:
        from fastapi import HTTPException
        raise HTTPException(status_code=400, detail=f"Deliverable Generation Failed: {error}")
        
    filename = os.path.basename(filepath) if filepath else f"generated.{output_format}"
    
    return GenerateResponse(
        filename=filename,
        file_path=filepath or f"./data/output/{filename}",
        format=output_format,
    )


# ── Workflows ────────────────────────────────────────────────────────────
from backend.api.schemas import WorkflowRequest
from backend.workflows.engine import workflow_engine

@router.post("/workflows/run", dependencies=[Depends(get_current_user)])
async def run_flagship_workflow(request: WorkflowRequest, current_user: dict = Depends(get_current_user)):
    """
    Execute a flagship SIH demo workflow.
    """
    trace = await workflow_engine.execute(
        user_role=current_user["role"],
        request_type=request.workflow_name,
        inputs=request.inputs
    )
    return trace.model_dump()


# ── Code Execution ────────────────────────────────────────────────────────────


@router.post("/execute", response_model=CodeExecutionResponse, dependencies=[Depends(require_permission("agent.execute_code"))])
async def execute_code(request: CodeExecutionRequest):
    """
    Execute code in a sandboxed Docker container.
    Network = disabled, memory/CPU limited, timeout enforced.
    """
    # TODO Phase 10: Implement Docker sandbox
    return CodeExecutionResponse(
        stdout="",
        stderr="Sandbox not yet implemented",
        exit_code=-1,
        execution_time_ms=0,
        files_created=[],
    )


# ── Authentication ────────────────────────────────────────────────────────────


class LoginRequest(BaseModel):
    """Login request body."""
    username: str
    password: str


@router.post("/auth/login")
async def login(request: LoginRequest):
    """
    Authenticate with username/password and receive a JWT token.
    All authentication is local — no external identity providers.
    """
    from backend.security.auth import authenticate_user, create_access_token

    user = authenticate_user(request.username, request.password)
    if not user:
        raise HTTPException(status_code=401, detail="Invalid credentials")

    token = create_access_token(
        data={"sub": user.username, "role": user.role}
    )
    return {
        "access_token": token,
        "token_type": "bearer",
        "user": {
            "username": user.username,
            "role": user.role,
            "department": user.department,
        },
    }


@router.get("/auth/me")
async def auth_me(current_user: dict = Depends(get_current_user)):
    """
    Decode a JWT token and return the current user.
    """
    return {
        "username": current_user["username"],
        "role": current_user["role"],
        "department": current_user["department"],
    }

# ── Admin Endpoints ───────────────────────────────────────────────────────────


@router.get("/admin/models", dependencies=[Depends(require_permission("all"))])
async def list_models():
    """List all available models and their current status."""
    from backend.optimization.vram import vram_manager
    models = get_all_models()
    gpu_status = vram_manager.get_state()

    return {
        "models": models,
        "active_gpu_model": "multi-model (dynamic)",
        "gpu_vram_total_mb": gpu_status.total_mb,
        "gpu_vram_used_mb": gpu_status.used_mb,
    }


@router.get("/admin/health", dependencies=[Depends(require_permission("all"))])
async def admin_health():
    """Detailed health check for all subsystems."""
    services = await probe_all(
        ollama_url=settings.ollama_base_url,
        qdrant_host=settings.qdrant_host,
        qdrant_port=settings.qdrant_port,
    )

    return {
        "api": "ok",
        "ollama": services["ollama"]["status"],
        "qdrant": services["qdrant"]["status"],
        "sandbox": "not_configured",  # TODO Phase 10
        "sovereignty": "enforced",
        "details": services,
    }
