"""
Sovereign AI Workbench — API Routes

All endpoint definitions for the workbench API.
Routes are wired to real backend components where available.

Phase 4: Added streaming chat, model management endpoints, and live inference metrics.
"""

import json
import uuid
import time
import logging
from typing import Optional

from fastapi import APIRouter, File, HTTPException, UploadFile
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from backend.api.schemas import (
    ChatRequest,
    ChatResponse,
    CodeExecutionRequest,
    CodeExecutionResponse,
    GenerateRequest,
    GenerateResponse,
    ModelStatus,
    RouteInfo,
    SearchRequest,
    SearchResponse,
    SystemStatus,
    TaskType,
    ModelName,
    UploadResponse,
)
from backend.router.model_registry import model_registry
from backend.router.task_classifier import task_classifier
from backend.router.router import model_router
from backend.router.ollama_client import ollama_client
from backend.api.health import probe_all
from backend.settings import settings

logger = logging.getLogger("sovereign.api.routes")

router = APIRouter()


# ── Chat / Query ───────────────────────────────────────────────────────────────


@router.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """
    Main chat endpoint. Classifies the task, routes to the appropriate model,
    executes tools as needed, and returns a response with sources.
    """
    start = time.time()
    request_id = str(uuid.uuid4())

    # Use the real task classifier
    classification = task_classifier.classify(
        request.message,
        has_image=False,
    )

    # Override with explicit request if provided
    task_type = request.task_type or classification.task_type
    model = request.model or classification.model

    # Attempt real model inference via the router
    try:
        result = await model_router.route(
            user_input=request.message,
            has_image=False,
        )
        response_text = result.get("response", "[No response from model]")
    except Exception as e:
        logger.warning("Model inference failed (expected if Ollama not running): %s", e)
        response_text = (
            f"[Sovereign AI] Task classified as '{task_type.value}' -> "
            f"model '{model.value}'. Inference backend not available: {e}"
        )

    duration = round((time.time() - start) * 1000, 2)

    return ChatResponse(
        response=response_text,
        route=RouteInfo(
            task_type=task_type,
            model=model,
            reason=classification.reason,
        ),
        sources=[],
        tools_used=[],
        files_created=[],
        sovereign=True,
        request_id=request_id,
        duration_ms=duration,
    )


@router.post("/chat/stream")
async def chat_stream(request: ChatRequest):
    """
    Streaming chat endpoint. Returns Server-Sent Events (SSE) as tokens
    are generated by the model.

    Each event:
        data: {"chunk": "token text", "done": false}
        ...
        data: {"chunk": "", "done": true, "classification": {...}, "metrics": {...}}
    """

    async def event_generator():
        try:
            async for chunk_data in model_router.route_stream(
                user_input=request.message,
                has_image=False,
            ):
                yield f"data: {json.dumps(chunk_data)}\n\n"
        except Exception as e:
            logger.error("Stream error: %s", e)
            error_event = {
                "chunk": f"[Error: {e}]",
                "done": True,
                "error": str(e),
            }
            yield f"data: {json.dumps(error_event)}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Sovereign": "true",
        },
    )


# ── Model Management ──────────────────────────────────────────────────────────


class ModelLoadRequest(BaseModel):
    """Request to load a model category."""
    category: str = Field(
        ...,
        description="Model category to load: reasoning, coding, vision, embedding, reranker",
    )


@router.post("/models/load")
async def load_model(request: ModelLoadRequest):
    """
    Explicitly load a model into VRAM. If another heavy model is loaded,
    it will be unloaded first (single-GPU discipline).
    """
    model_config = model_registry.get_model(request.category)
    if not model_config:
        raise HTTPException(
            status_code=404,
            detail=f"Unknown model category: {request.category}",
        )

    # Check if model is available in Ollama
    available = await model_registry.ensure_model_available(request.category)
    if not available:
        raise HTTPException(
            status_code=503,
            detail=(
                f"Model '{model_config.model_id}' is not pulled in Ollama. "
                f"Run: ollama pull {model_config.model_id}"
            ),
        )

    start = time.time()
    loaded = await model_registry.load_model(request.category)
    duration = round((time.time() - start) * 1000, 2)

    return {
        "status": "loaded",
        "model": loaded.name,
        "model_id": loaded.model_id,
        "category": request.category,
        "vram_used_mb": loaded.vram_used_mb,
        "load_time_ms": duration,
        "active_heavy_model": model_registry.get_active_heavy_model(),
    }


@router.post("/models/unload")
async def unload_model(request: ModelLoadRequest):
    """Explicitly unload a model from VRAM."""
    model_config = model_registry.get_model(request.category)
    if not model_config:
        raise HTTPException(
            status_code=404,
            detail=f"Unknown model category: {request.category}",
        )

    await model_registry.unload_model(request.category)

    return {
        "status": "unloaded",
        "model": model_config.name,
        "category": request.category,
        "active_heavy_model": model_registry.get_active_heavy_model(),
    }


@router.get("/models/status")
async def models_status():
    """
    Real GPU status from Ollama ps + registry state.
    Shows which models are loaded, VRAM usage, and available capacity.
    """
    # Sync registry with Ollama's actual state
    await model_registry.sync_with_ollama()

    models = model_registry.list_models()
    gpu_status = await model_registry.get_gpu_status()

    return {
        "models": models,
        "gpu": gpu_status,
        "sovereign": True,
    }


@router.get("/models/available")
async def list_available_models():
    """
    List all models available in Ollama (pulled and ready to use).
    """
    models = await ollama_client.list_models()

    return {
        "ollama_models": [
            {
                "name": m.name,
                "size_gb": m.size_gb,
                "parameter_size": m.parameter_size,
                "quantization": m.quantization_level,
                "family": m.family,
            }
            for m in models
        ],
        "total": len(models),
    }


# ── Document Upload ────────────────────────────────────────────────────────────


@router.post("/upload", response_model=UploadResponse)
async def upload_document(
    file: UploadFile = File(...),
    department: Optional[str] = None,
    access_level: str = "engineering",
):
    """
    Upload a document for processing. The pipeline will:
    1. Detect document type
    2. Run Docling for layout extraction
    3. Run PaddleOCR for scanned pages
    4. Chunk and embed
    5. Store in Qdrant with metadata
    """
    start = time.time()
    doc_id = f"DOC-{uuid.uuid4().hex[:8].upper()}"

    # TODO Phase 12-15: Implement actual document ingestion pipeline
    duration = round((time.time() - start) * 1000, 2)

    return UploadResponse(
        document_id=doc_id,
        filename=file.filename or "unknown",
        pages=0,
        chunks=0,
        status="pending_implementation",
        processing_time_ms=duration,
    )


# ── RAG Search ─────────────────────────────────────────────────────────────────


@router.post("/search", response_model=SearchResponse)
async def search_documents(request: SearchRequest):
    """
    Hybrid search: dense (Qdrant) + BM25 -> merge -> rerank -> top K.
    RBAC filtering is applied BEFORE retrieval.
    """
    # TODO Phase 14-17: Implement actual RAG pipeline
    return SearchResponse(
        results=[],
        query=request.query,
        total_found=0,
        reranked=request.rerank,
    )


# ── Document Generation ───────────────────────────────────────────────────────


@router.post("/generate", response_model=GenerateResponse)
async def generate_document(request: GenerateRequest):
    """
    Generate enterprise documents (DOCX, XLSX, PPTX) from AI analysis.
    """
    # TODO Phase 20: Implement document generators
    return GenerateResponse(
        filename=f"generated.{request.output_format}",
        file_path=f"./data/output/generated.{request.output_format}",
        format=request.output_format,
    )


# ── Code Execution ────────────────────────────────────────────────────────────


@router.post("/execute", response_model=CodeExecutionResponse)
async def execute_code(request: CodeExecutionRequest):
    """
    Execute code in a sandboxed Docker container.
    Network = disabled, memory/CPU limited, timeout enforced.
    """
    # TODO Phase 10: Implement Docker sandbox
    return CodeExecutionResponse(
        stdout="",
        stderr="Sandbox not yet implemented",
        exit_code=-1,
        execution_time_ms=0,
        files_created=[],
    )


# ── Authentication ────────────────────────────────────────────────────────────


class LoginRequest(BaseModel):
    """Login request body."""
    username: str
    password: str


@router.post("/auth/login")
async def login(request: LoginRequest):
    """
    Authenticate with username/password and receive a JWT token.
    All authentication is local — no external identity providers.
    """
    from backend.security.auth import authenticate_user, create_access_token

    user = authenticate_user(request.username, request.password)
    if not user:
        raise HTTPException(status_code=401, detail="Invalid credentials")

    token = create_access_token(
        data={"sub": user.username, "role": user.role}
    )
    return {
        "access_token": token,
        "token_type": "bearer",
        "user": {
            "username": user.username,
            "role": user.role,
            "department": user.department,
        },
    }


@router.get("/auth/me")
async def get_current_user(token: str = ""):
    """
    Decode a JWT token and return the current user.
    Pass the token as a query parameter for simplicity in Phase 3.
    """
    from backend.security.auth import decode_token, DEMO_USERS, User

    if not token:
        raise HTTPException(status_code=401, detail="Token required")

    token_data = decode_token(token)
    if not token_data or not token_data.username:
        raise HTTPException(status_code=401, detail="Invalid or expired token")

    user_data = DEMO_USERS.get(token_data.username)
    if not user_data:
        raise HTTPException(status_code=404, detail="User not found")

    return {
        "username": user_data["username"],
        "role": user_data["role"],
        "department": user_data["department"],
    }


# ── Admin Endpoints ───────────────────────────────────────────────────────────


@router.get("/admin/models")
async def list_models():
    """List all available models and their current status."""
    models = model_registry.list_models()
    gpu_status = await model_registry.get_gpu_status()

    return {
        "models": models,
        "active_gpu_model": gpu_status["active_heavy_model"],
        "gpu_vram_total_mb": gpu_status["total_vram_mb"],
        "gpu_vram_used_mb": gpu_status["used_vram_mb"],
    }


@router.get("/admin/health")
async def admin_health():
    """Detailed health check for all subsystems."""
    services = await probe_all(
        ollama_url=settings.ollama_base_url,
        qdrant_host=settings.qdrant_host,
        qdrant_port=settings.qdrant_port,
    )

    return {
        "api": "ok",
        "ollama": services["ollama"]["status"],
        "qdrant": services["qdrant"]["status"],
        "sandbox": "not_configured",  # TODO Phase 10
        "sovereignty": "enforced",
        "details": services,
    }
