"""
Sovereign AI Workbench — API Routes

All endpoint definitions for the workbench API.
Routes are wired to real backend components where available.

Phase 4: Added streaming chat, model management endpoints, and live inference metrics.
Phase 6: Added /classify endpoint for routing preview without inference.
Phase 7: Added /code/generate endpoint for structured code generation.
"""

import json
import uuid
import time
import logging
from typing import Optional, List, Dict, Any

from fastapi import APIRouter, File, HTTPException, UploadFile, Depends, Request, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from backend.api.schemas import (
    ChatRequest,
    ChatResponse,
    ClassifyRequest,
    ClassifyResponse,
    ClassificationSignalSchema,
    CodeBlockSchema,
    CodeExecutionRequest,
    CodeExecutionResponse,
    CodeGenerateRequest,
    CodeGenerateResponse,
    GenerateRequest,
    GenerateResponse,
    ModelStatus,
    RouteInfo,
    RoutingDecisionSchema,
    SearchRequest,
    SearchResponse,
    SystemStatus,
    TaskType,
    ModelName,
    UploadResponse,
    VisionAnalyzeRequest,
    VisionAnalyzeResponse,
)
from backend.models.registry import get_all_models
from backend.router.task_classifier import task_classifier
from backend.router.router import model_router
from backend.router.ollama_client import ollama_client
from backend.router.coding import extract_code_blocks
from backend.api.health import probe_all
from backend.settings import settings
from backend.security.dependencies import require_permission, get_current_user

logger = logging.getLogger("sovereign.api.routes")

router = APIRouter()


# ── Chat / Query ───────────────────────────────────────────────────────────────


@router.post("/chat", response_model=ChatResponse, dependencies=[Depends(require_permission("ai.chat"))])
async def chat(request: ChatRequest):
    """
    Main chat endpoint. Classifies the task, routes to the appropriate model,
    executes tools as needed, and returns a response with sources.
    """
    start = time.time()
    request_id = str(uuid.uuid4())
    session_id = request.session_id or request_id

    # Use the real task classifier
    classification = task_classifier.classify(
        request.message,
        has_image=bool(request.images),
    )

    # Override with explicit request if provided
    task_type = request.task_type or classification.task_type
    model = request.model or classification.model

    # Attempt real model inference via the router
    try:
        result = await model_router.route(
            user_input=request.message,
            images=request.images,
            force_model=request.model,
            session_id=session_id,
        )
        response_text = result.get("response", "[No response from model]")
    except Exception as e:
        logger.warning("Model inference failed (expected if Ollama not running): %s", e)
        response_text = (
            f"[Sovereign AI] Task classified as '{task_type.value}' -> "
            f"model '{model.value}'. Inference backend not available: {e}"
        )

    duration = round((time.time() - start) * 1000, 2)

    return ChatResponse(
        response=response_text,
        route=RouteInfo(
            task_type=task_type,
            model=model,
            reason=classification.reason,
        ),
        sources=[],
        tools_used=[],
        files_created=[],
        sovereign=True,
        request_id=request_id,
        duration_ms=duration,
    )


@router.post("/chat/stream", dependencies=[Depends(require_permission("ai.chat"))])
async def chat_stream(request: ChatRequest):
    """
    Streaming chat endpoint. Returns Server-Sent Events (SSE) as tokens
    are generated by the model.

    Each event:
        data: {"chunk": "token text", "done": false}
        ...
        data: {"chunk": "", "done": true, "classification": {...}, "metrics": {...}}
    """
    session_id = request.session_id or str(uuid.uuid4())

    async def event_generator():
        try:
            async for chunk_data in model_router.route_stream(
                user_input=request.message,
                images=request.images,
                force_model=request.model,
                session_id=session_id,
            ):
                yield f"data: {json.dumps(chunk_data)}\n\n"
        except Exception as e:
            logger.error("Stream error: %s", e)
            error_event = {
                "chunk": f"[Error: {e}]",
                "done": True,
                "error": str(e),
            }
            yield f"data: {json.dumps(error_event)}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Sovereign": "true",
        },
    )


# ── Classification (Phase 6) ───────────────────────────────────────────────────


@router.post("/classify", response_model=ClassifyResponse, dependencies=[Depends(require_permission("ai.chat"))])
async def classify_input(request: ClassifyRequest):
    """
    Classify a user input and return the routing decision WITHOUT running
    model inference. Shows which model would be selected and why.

    This is the Dynamic Expertise Broker made visible — the frontend can
    display "This would be routed to Qwen2.5-Coder-7B because..." before
    the user commits to running the full inference.
    """
    try:
        decision = await model_router.classify_only(
            user_input=request.message,
            has_image=request.has_image,
            use_llm=request.use_llm,
        )
    except Exception as e:
        logger.error("Classification failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Classification error: {e}")

    # Build response with optional pattern explanation
    explanation = task_classifier.explain(request.message)

    # Convert signals to schema types
    kw_signal = None
    if decision.keyword_signal:
        kw_signal = ClassificationSignalSchema(
            source=decision.keyword_signal.source,
            task_type=decision.keyword_signal.task_type,
            model=decision.keyword_signal.model,
            confidence=decision.keyword_signal.confidence,
            reason=decision.keyword_signal.reason,
            duration_ms=decision.keyword_signal.duration_ms,
        )

    llm_signal = None
    if decision.llm_signal:
        llm_signal = ClassificationSignalSchema(
            source=decision.llm_signal.source,
            task_type=decision.llm_signal.task_type,
            model=decision.llm_signal.model,
            confidence=decision.llm_signal.confidence,
            reason=decision.llm_signal.reason,
            duration_ms=decision.llm_signal.duration_ms,
        )

    return ClassifyResponse(
        routing_decision=RoutingDecisionSchema(
            task_type=decision.task_type,
            model_category=decision.model_category,
            model_name=decision.model_name,
            confidence=decision.confidence,
            reason=decision.reason,
            used_llm=decision.used_llm,
            total_classification_ms=decision.total_classification_ms,
            keyword_signal=kw_signal,
            llm_signal=llm_signal,
            policy={
                "llm_threshold": decision.policy_llm_threshold,
                "prefer_llm": decision.policy_prefer_llm,
            },
        ),
        explanation=explanation,
    )


# ── Code Generation (Phase 7) ─────────────────────────────────────────────────


@router.post("/code/generate", response_model=CodeGenerateResponse, dependencies=[Depends(require_permission("agent.execute_code"))])
async def generate_code(request: CodeGenerateRequest):
    """
    Generate code using the specialized coder model (Qwen2.5-Coder-7B).

    Returns structured code blocks extracted from the model response,
    plus the raw response and routing metadata. This is the precursor
    to the Phase 10 sandbox integration where generated code will be
    executed in a Docker container.

    Flow:
        Prompt → Coder Model → Raw Response → Code Block Extraction → Structured Output
    """
    start = time.time()

    try:
        result = await model_router.generate_code(
            prompt=request.prompt,
            language=request.language,
            context=request.context,
            temperature=request.temperature,
            max_tokens=request.max_tokens,
        )
    except Exception as e:
        logger.error("Code generation failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Code generation error: {e}")

    duration_ms = round((time.time() - start) * 1000, 2)

    return CodeGenerateResponse(
        code_blocks=[
            CodeBlockSchema(
                language=b.language,
                code=b.code,
                description=b.description,
                line_count=b.line_count,
            )
            for b in result.code_blocks
        ],
        raw_response=result.raw_response,
        route=RouteInfo(
            task_type=TaskType.CODING,
            model=ModelName.QWEN25_CODER_7B,
            reason="Forced to coder model for code generation",
        ),
        model_used=result.model_used,
        duration_ms=duration_ms,
        total_lines=result.total_lines,
    )



# ── Vision Endpoints (Phase 8) ────────────────────────────────────────────────

@router.post("/vision/analyze", response_model=VisionAnalyzeResponse, dependencies=[Depends(require_permission("ai.vision"))])
async def analyze_vision(request: VisionAnalyzeRequest):
    """
    Dedicated endpoint for vision analysis.
    Forces the vision model and specialized system prompt.
    """
    # Validate images are non-empty
    if not request.images or all(not img.strip() for img in request.images):
        raise HTTPException(status_code=422, detail="At least one non-empty image is required.")

    try:
        result = await model_router.analyze_vision(
            prompt=request.prompt,
            images=request.images,
            temperature=request.temperature,
            max_tokens=request.max_tokens,
        )

        if not result.success:
            raise HTTPException(
                status_code=500,
                detail=result.error or "Vision analysis failed with no error details.",
            )

        return VisionAnalyzeResponse(
            content=result.content,
            route=RouteInfo(
                task_type=TaskType.VISION,
                model=ModelName.QWEN3_VL_8B,
                reason="Dedicated vision route using the local vision model",
            ),
            model_used=result.model_used or settings.ollama_vision_model,
            duration_ms=result.duration_ms,
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ── Document Upload ────────────────────────────────────────────────────────────


@router.post("/upload", response_model=UploadResponse, dependencies=[Depends(require_permission("document.upload"))])
async def upload_document(
    file: UploadFile = File(...),
    department: Optional[str] = None,
    access_level: str = "engineering",
    description: Optional[str] = None,
):
    """
    Upload a document for processing. The pipeline will:
    1. Detect document type
    2. Run Docling for layout extraction (or fallback)
    3. Run PaddleOCR for scanned pages (Phase 13+)
    4. Chunk and embed
    5. Store in Qdrant with metadata
    """
    from backend.documents.ingest import ingestion_pipeline
    import shutil
    import os
    from pathlib import Path
    
    start = time.time()
    
    # Save uploaded file to temp/uploads directory
    upload_dir = Path("data/uploads")
    upload_dir.mkdir(parents=True, exist_ok=True)
    
    safe_filename = Path(file.filename or "unknown.pdf").name
    file_path = upload_dir / f"{uuid.uuid4().hex[:8]}_{safe_filename}"
    
    try:
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
            
        result = await ingestion_pipeline.ingest(
            file_path=str(file_path),
            department=department or "engineering",
            access_level=access_level,
            description=description,
        )
        
        # Cleanup uploaded file for zero-egress/ephemeral policy
        if file_path.exists():
            file_path.unlink()
            
    except Exception as e:
        logger.error("Upload failed: %s", e)
        raise HTTPException(status_code=500, detail=str(e))

    return UploadResponse(
        document_id=result.document_id,
        filename=result.filename,
        pages=result.pages,
        chunks=result.chunks,
        status=result.status,
        processing_time_ms=result.processing_time_ms,
    )


# ── RAG Search ─────────────────────────────────────────────────────────────────


@router.post("/search", response_model=SearchResponse, dependencies=[Depends(require_permission("rag.search"))])
async def search_documents(request: SearchRequest):
    """
    Hybrid search: dense (Qdrant) + BM25 -> merge -> rerank -> top K.
    RBAC filtering is applied BEFORE retrieval.
    """
    from backend.rag.embedder import embedding_service
    from backend.rag.retriever import hybrid_retriever
    from backend.rag.reranker import reranker_service
    from backend.api.schemas import SourceDocument
    from backend.rag.exceptions import RetrievalServiceError

    try:
        # 1. Embed query
        query_embedding = await embedding_service.embed_text(request.query)
    
        # 2. Hybrid search with RBAC
        candidates = await hybrid_retriever.search(
            query=request.query,
            query_embedding=query_embedding,
            top_k=request.top_k * 2 if request.rerank else request.top_k,
            user_role=request.user_role.value if hasattr(request.user_role, 'value') else request.user_role,
            department_filter=request.department_filter,
        )
    
        # 3. Rerank
        if request.rerank and candidates:
            candidates = await reranker_service.rerank(
                query=request.query,
                documents=candidates,
                top_k=request.top_k,
            )
    except RetrievalServiceError as e:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(e)
        )
        
    # 4. Format response
    source_docs = []
    for doc in candidates:
        source_docs.append(
            SourceDocument(
                document_id=doc.get("document_id", "unknown"),
                title=doc.get("filename") or doc.get("title") or "Document",
                page=doc.get("page"),
                relevance_score=doc.get("_rerank_score") if request.rerank else doc.get("_rrf_score", 0.0),
                snippet=doc.get("text", "")[:500] + "...",
            )
        )

    return SearchResponse(
        results=source_docs,
        query=request.query,
        total_found=len(source_docs),
        reranked=request.rerank,
    )


# ── Document Generation ───────────────────────────────────────────────────────
from backend.generators.service import deliverable_service
import os


@router.post("/generate", response_model=GenerateResponse, dependencies=[Depends(require_permission("report.create"))])
async def generate_document(request: GenerateRequest):
    """
    Generate enterprise documents (DOCX, XLSX, PPTX) from AI analysis.
    """
    output_format = request.output_format.lower()
    title = request.source_data.get("title", f"Generated_{request.request_type}")
    
    filepath = ""
    error = ""
    if output_format == "docx":
        filepath, error = await deliverable_service.create_and_validate_docx(
            title=title, content=request.source_data, template=request.template
        )
    elif output_format == "xlsx":
        filepath, error = await deliverable_service.create_and_validate_xlsx(
            title=title,
            data=request.source_data.get("data", []),
            summary=request.source_data.get("summary")
        )
    elif output_format == "pptx":
        filepath, error = await deliverable_service.create_and_validate_pptx(
            title=title,
            slides=request.source_data.get("slides", [])
        )
    elif output_format == "zip":
        filepath, error = await deliverable_service.create_and_validate_code_package(
            title=title,
            files=request.source_data.get("files", {})
        )
        
    if error:
        from fastapi import HTTPException
        raise HTTPException(status_code=400, detail=f"Deliverable Generation Failed: {error}")
        
    filename = os.path.basename(filepath) if filepath else f"generated.{output_format}"
    
    return GenerateResponse(
        filename=filename,
        file_path=filepath or f"./data/output/{filename}",
        format=output_format,
    )


# ── Workflows ────────────────────────────────────────────────────────────
from backend.api.schemas import WorkflowRequest
from backend.workflows.engine import workflow_engine
from backend.security.rbac import rbac_enforcer

@router.post("/workflows/run", dependencies=[Depends(get_current_user)])
async def run_flagship_workflow(request: WorkflowRequest, current_user: dict = Depends(get_current_user)):
    """
    Execute a flagship workflow with RBAC enforcement.
    The user's role must have access to the requested workflow.
    """
    user_role = current_user["role"]
    if not rbac_enforcer.can_access_workflow(user_role, request.workflow_name):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=f"Role '{user_role}' does not have access to workflow '{request.workflow_name}'",
        )
    trace = await workflow_engine.execute(
        user_role=user_role,
        request_type=request.workflow_name,
        inputs=request.inputs
    )
    return trace.model_dump()


@router.get("/workflows/available")
async def get_available_workflows(current_user: dict = Depends(get_current_user)):
    """
    Return the list of workflows the current user can access,
    based on their RBAC role.
    """
    user_role = current_user["role"]
    workflows = rbac_enforcer.get_accessible_workflows(user_role)
    return {
        "role": user_role,
        "workflows": workflows,
    }


# ── Code Execution ────────────────────────────────────────────────────────────


@router.post("/execute", response_model=CodeExecutionResponse, dependencies=[Depends(require_permission("agent.execute_code"))])
async def execute_code(request: CodeExecutionRequest):
    """
    Execute code in an isolated sandbox environment.
    Network = disabled, memory/CPU limited, timeout enforced, with local fallback.
    """
    import asyncio
    from backend.tools.python_sandbox import run_python_code

    start_time = time.time()
    try:
        result = await asyncio.to_thread(
            run_python_code,
            request.code,
            timeout=request.timeout_seconds,
        )
        duration_ms = round((time.time() - start_time) * 1000, 2)
        return CodeExecutionResponse(
            stdout=result.stdout,
            stderr=result.stderr,
            exit_code=result.exit_code,
            execution_time_ms=duration_ms,
            files_created=[],
        )
    except Exception as e:
        logger.error("Code execution failed: %s", e)
        duration_ms = round((time.time() - start_time) * 1000, 2)
        return CodeExecutionResponse(
            stdout="",
            stderr=str(e),
            exit_code=-1,
            execution_time_ms=duration_ms,
            files_created=[],
        )


# ── Authentication ────────────────────────────────────────────────────────────


class LoginRequest(BaseModel):
    """Login request body."""
    username: str
    password: str


@router.post("/auth/login")
async def login(request: Request):
    """
    Authenticate with username/password and receive a JWT token.
    All authentication is local — no external identity providers.
    Supports both JSON payloads and Form Data.
    """
    from datetime import timedelta
    from backend.security.auth import authenticate_user, create_access_token

    username = None
    password = None
    remember_me = False

    content_type = request.headers.get("content-type", "")
    if "application/json" in content_type:
        try:
            body = await request.json()
            if isinstance(body, dict):
                username = body.get("username")
                password = body.get("password")
                remember_me = bool(body.get("remember_me", False))
        except Exception:
            raise HTTPException(status_code=400, detail="Invalid JSON body")
    else:
        try:
            form = await request.form()
            username = form.get("username")
            password = form.get("password")
            remember_me = bool(form.get("remember_me", False))
        except Exception:
            pass
        if not username or not password:
            try:
                body = await request.json()
                if isinstance(body, dict):
                    username = body.get("username")
                    password = body.get("password")
                    remember_me = bool(body.get("remember_me", False))
            except Exception:
                pass

    if not username or not password:
        raise HTTPException(status_code=422, detail="Username and password are required")

    user = authenticate_user(str(username), str(password))
    if not user:
        raise HTTPException(status_code=401, detail="Invalid credentials")

    expires_delta = timedelta(days=30) if remember_me else None
    token = create_access_token(
        data={"sub": user.username, "role": user.role},
        expires_delta=expires_delta,
    )
    return {
        "access_token": token,
        "token_type": "bearer",
        "user": {
            "username": user.username,
            "role": user.role,
            "department": user.department,
        },
    }


class SignUpRequest(BaseModel):
    username: str
    password: str
    role: str = "engineering"
    department: Optional[str] = None
    remember_me: bool = False


@router.post("/auth/signup")
async def signup_user(request: SignUpRequest):
    """
    Public self-registration endpoint.
    Creates a new user account and returns an access token.
    """
    from datetime import timedelta
    from backend.security.auth import user_store, create_access_token

    username = request.username.strip()
    password = request.password
    if not username or not password:
        raise HTTPException(status_code=422, detail="Username and password are required")

    if len(password) < 4:
        raise HTTPException(status_code=422, detail="Password must be at least 4 characters")

    role = request.role.lower().strip()
    valid_roles = ("admin", "engineering", "finance", "operations", "procurement", "hr")
    if role not in valid_roles:
        role = "engineering"

    dept_map = {
        "admin": "all",
        "engineering": "engineering",
        "finance": "finance",
        "operations": "operations",
        "procurement": "procurement",
        "hr": "hr",
    }
    dept = request.department or dept_map.get(role, "engineering")

    try:
        user_data = user_store.create_user(
            username=username,
            password=password,
            role=role,
            department=dept,
        )
    except ValueError:
        raise HTTPException(status_code=409, detail=f"Username '{username}' already exists")

    expires_delta = timedelta(days=30) if request.remember_me else None
    token = create_access_token(
        data={"sub": user_data["username"], "role": user_data["role"]},
        expires_delta=expires_delta,
    )
    return {
        "access_token": token,
        "token_type": "bearer",
        "user": {
            "username": user_data["username"],
            "role": user_data["role"],
            "department": user_data["department"],
        },
    }


@router.get("/auth/me")
async def auth_me(current_user: dict = Depends(get_current_user)):
    """
    Decode a JWT token and return the current user.
    """
    return {
        "username": current_user["username"],
        "role": current_user["role"],
        "department": current_user["department"],
    }


class RegisterRequest(BaseModel):
    """Register a new user (admin only)."""
    username: str
    password: str
    role: str
    department: str


@router.post("/auth/register", dependencies=[Depends(require_permission("all"))])
async def register_user(request: RegisterRequest):
    """
    Create a new user account. Admin-only.
    """
    from backend.security.auth import user_store

    try:
        user_data = user_store.create_user(
            username=request.username,
            password=request.password,
            role=request.role,
            department=request.department,
        )
    except ValueError as e:
        raise HTTPException(status_code=409, detail=str(e))

    return {
        "message": f"User '{request.username}' created successfully",
        "user": {
            "username": user_data["username"],
            "role": user_data["role"],
            "department": user_data["department"],
        },
    }


@router.get("/auth/users", dependencies=[Depends(require_permission("all"))])
async def list_users():
    """
    List all registered users. Admin-only.
    """
    from backend.security.auth import user_store
    return {"users": user_store.list_users()}

# ── Admin Endpoints ───────────────────────────────────────────────────────────


@router.get("/admin/models", dependencies=[Depends(require_permission("all"))])
async def list_models():
    """List all available models and their current status."""
    from backend.optimization.vram import vram_manager
    models = get_all_models()
    gpu_status = vram_manager.get_state()

    return {
        "models": models,
        "active_gpu_model": "multi-model (dynamic)",
        "gpu_vram_total_mb": gpu_status.total_mb,
        "gpu_vram_used_mb": gpu_status.used_mb,
    }


@router.get("/admin/health", dependencies=[Depends(require_permission("all"))])
async def admin_health():
    """Detailed health check for all subsystems."""
    services = await probe_all(
        ollama_url=settings.ollama_base_url,
        qdrant_host=settings.qdrant_host,
        qdrant_port=settings.qdrant_port,
    )

    return {
        "api": "ok",
        "ollama": services["ollama"]["status"],
        "qdrant": services["qdrant"]["status"],
        "sandbox": "not_configured",  # TODO Phase 10
        "sovereignty": "enforced",
        "details": services,
    }


# ── Strategic Sovereign Architecture Endpoints ───────────────────────────────

# 1. Cryptographic Attestation & TEE Endpoints
@router.post("/attestation/challenge")
async def attestation_challenge():
    """Generates a cryptographically random session nonce for TEE attestation."""
    from backend.security.attestation import attestation_gateway
    nonce = attestation_gateway.generate_challenge_nonce()
    return {"nonce": nonce, "enclave_type": attestation_gateway.enclave_type.value}


@router.get("/attestation/report")
async def attestation_report():
    """Retrieves the current hardware enclave measurement and TCB state."""
    from backend.security.attestation import attestation_gateway
    meas = attestation_gateway.get_active_measurement()
    return meas.to_dict()


class AttestationVerifyRequest(BaseModel):
    nonce: str
    quote_hex: Optional[str] = None


@router.post("/attestation/verify")
async def attestation_verify(req: AttestationVerifyRequest):
    """Verifies a hardware quote against the manufacturer root of trust."""
    from backend.security.attestation import attestation_gateway
    from backend.security.tamper_proof_audit import merkle_audit_ledger

    report = attestation_gateway.verify_quote(req.nonce, req.quote_hex)
    merkle_audit_ledger.append_event(
        event_type="TEE_ATTESTATION_VERIFIED",
        actor_id="TEE_GATEWAY",
        payload={"is_valid": report.is_valid, "enclave_type": report.enclave_type, "pcr_quote": report.pcr_quote_hash}
    )
    return report.to_dict()


@router.post("/attestation/export-proofs")
async def attestation_export_proofs(req: AttestationVerifyRequest):
    """Generates the triple-file proof package (HTML cert, binary quote, and signed JSON)."""
    from backend.security.attestation import attestation_gateway
    report = attestation_gateway.verify_quote(req.nonce, req.quote_hex)
    proofs = attestation_gateway.generate_triple_file_proofs(report)
    return proofs


# 2. Advanced MCP Governance Firewall & ZKP Gateway
class MCPEvaluateRequest(BaseModel):
    tool_name: str
    arguments: dict
    user_id: str
    role: str
    jurisdiction: str = "IN_COUNTRY"


@router.post("/mcp/evaluate-tool")
async def mcp_evaluate_tool(req: MCPEvaluateRequest):
    """Evaluates an LLM tool call against the MCP firewall policies."""
    from backend.security.mcp_firewall import mcp_governance_firewall
    from backend.security.tamper_proof_audit import merkle_audit_ledger

    decision = mcp_governance_firewall.evaluate_invocation(
        tool_name=req.tool_name,
        arguments=req.arguments,
        user_id=req.user_id,
        user_role=req.role,
        jurisdiction=req.jurisdiction
    )
    merkle_audit_ledger.append_event(
        event_type="MCP_FIREWALL_EVALUATION",
        actor_id=req.user_id,
        payload={"tool": req.tool_name, "allowed": decision.allowed, "violation": decision.violation_reason}
    )
    return decision.to_dict()


@router.get("/mcp/active-tokens")
async def mcp_active_tokens():
    """Returns active single-use MCP execution tokens."""
    from backend.security.mcp_firewall import mcp_governance_firewall
    tokens = mcp_governance_firewall.get_active_tokens()
    return {"active_tokens": [t.to_dict() for t in tokens]}


class ZKPRangeProofRequest(BaseModel):
    value: int
    threshold: int
    operator: str = "<="
    predicate_name: str = "budget_limit"


@router.post("/zkp/generate-range-proof")
async def zkp_generate_range_proof(req: ZKPRangeProofRequest):
    """Generates a zero-knowledge range proof without revealing the plaintext value."""
    from backend.security.zkp_gateway import zkp_gateway
    proof = zkp_gateway.generate_range_proof(
        value=req.value,
        threshold=req.threshold,
        operator=req.operator,
        predicate_name=req.predicate_name
    )
    return proof.to_dict()


class ZKPVerifyProofRequest(BaseModel):
    proof: dict


@router.post("/zkp/verify-proof")
async def zkp_verify_proof(req: ZKPVerifyProofRequest):
    """Verifies a zero-knowledge predicate proof."""
    from backend.security.zkp_gateway import zkp_gateway, ZKPProof
    p = ZKPProof(**req.proof)
    valid = zkp_gateway.verify_proof(p)
    return {"valid": valid, "predicate": p.predicate, "commitment": p.commitment}


# 3. Culturally Adaptive Tokenization & Hardware Co-Design
class AdaptiveTokenizeRequest(BaseModel):
    text: str


@router.post("/nlp/adaptive-tokenization")
async def nlp_adaptive_tokenization(req: AdaptiveTokenizeRequest):
    """Applies script-aware normalization and calculates token density metrics."""
    from backend.nlp.adaptive_tokenization import adaptive_tokenizer
    return adaptive_tokenizer.process_text(req.text)


class HardwareManifestRequest(BaseModel):
    model_id: str = "qwen2.5-coder:7b"
    parameter_count_b: float = 7.0
    vocab_size: int = 152064
    context_window: int = 32768
    architecture: str = "dense"
    target_precision: str = "int4"
    target_silicon: Optional[str] = None
    enforce_confidential: bool = False


@router.post("/optimization/hardware-manifest")
async def optimization_hardware_manifest(req: HardwareManifestRequest):
    """Generates silicon hardware co-design deployment manifest."""
    from backend.optimization.hardware_mapping import hardware_co_design_mapper, ModelProfile
    profile = ModelProfile(
        model_id=req.model_id,
        parameter_count_b=req.parameter_count_b,
        vocab_size=req.vocab_size,
        context_window=req.context_window,
        architecture=req.architecture,
        target_precision=req.target_precision
    )
    manifest = hardware_co_design_mapper.generate_manifest(
        profile=profile,
        target_name=req.target_silicon,
        enforce_confidential=req.enforce_confidential
    )
    return manifest.to_dict()


# 4. Verifiable RAG with Evidence-Sufficiency Gate
class VerifiableRAGQueryRequest(BaseModel):
    query: str
    documents: List[dict]
    user_clearance: str = "INTERNAL"
    similarity_threshold: float = 0.65


@router.post("/rag/verifiable-query")
async def rag_verifiable_query(req: VerifiableRAGQueryRequest):
    """Executes layout-preserving segmentation, Evidence-Sufficiency Gate, and Provenance Guardrail."""
    from backend.rag.verifiable_rag import verifiable_rag_engine, VerifiableChunk
    from backend.security.tamper_proof_audit import merkle_audit_ledger

    chunks = []
    for d in req.documents:
        chunks.append(VerifiableChunk(
            chunk_id=d.get("chunk_id", "CHK-DEMO"),
            doc_id=d.get("doc_id", "DOC-1"),
            content=d.get("content", ""),
            metadata=d.get("metadata", {}),
            content_hash=d.get("content_hash", "abc"),
            clearance_required=d.get("clearance_required", "INTERNAL"),
            similarity_score=float(d.get("similarity_score", 0.7))
        ))

    gate_result = verifiable_rag_engine.evaluate_evidence_sufficiency(
        chunks=chunks,
        user_clearance=req.user_clearance,
        threshold=req.similarity_threshold
    )

    dummy_answer = f"According to verified documentation [{chunks[0].chunk_id}], the system configuration is operational." if gate_result.sufficient else ""

    response = verifiable_rag_engine.enforce_provenance_guardrails(
        query=req.query,
        generated_answer=dummy_answer,
        evidence_result=gate_result
    )

    merkle_audit_ledger.append_event(
        event_type="VERIFIABLE_RAG_EVALUATION",
        actor_id="RAG_GATEWAY",
        payload={"query": req.query, "gate": response.evidence_gate_status, "verified": response.verified}
    )

    return response.to_dict()


# 5. Infrastructure Telemetry & Sustainability Control
@router.get("/telemetry/fusion")
async def telemetry_fusion():
    """Returns multi-domain physical telemetry snapshot and carbon cost recommendations."""
    from backend.telemetry.fusion_engine import telemetry_fusion_engine
    snapshot = telemetry_fusion_engine.sample_sensors()
    return snapshot.to_dict()


class UpdateCarbonRequest(BaseModel):
    grid_carbon_intensity_gco2_kwh: float


@router.post("/telemetry/update-carbon")
async def telemetry_update_carbon(req: UpdateCarbonRequest):
    """Updates real-time regional grid carbon intensity."""
    from backend.telemetry.fusion_engine import telemetry_fusion_engine
    telemetry_fusion_engine.update_grid_carbon_intensity(req.grid_carbon_intensity_gco2_kwh)
    return {"status": "updated", "grid_carbon_intensity": req.grid_carbon_intensity_gco2_kwh}


# 6. Multi-Backend Orchestrator & Fallback
class RouteEvaluationRequest(BaseModel):
    task_type: str = "coding"
    user_role: str = "software_engineer"
    required_context_length: int = 4096
    allow_egress: bool = False


@router.post("/router/sovereign-fallback")
async def router_sovereign_fallback(req: RouteEvaluationRequest):
    """Evaluates 3-tier sovereign fallback destination."""
    from backend.router.fallback_orchestrator import fallback_orchestrator
    result = fallback_orchestrator.evaluate_route(
        task_type=req.task_type,
        user_role=req.user_role,
        required_context_length=req.required_context_length,
        allow_egress=req.allow_egress
    )
    return result.to_dict()


# 7. Mantic Scaffold Meta-Prompting
class ManticScaffoldRequest(BaseModel):
    objective: str
    custom_layers: Optional[List[dict]] = None


@router.post("/meta/mantic-scaffold")
async def meta_mantic_scaffold(req: ManticScaffoldRequest):
    """Calculates M-Score, inter-layer Coherence, and generates compositional execution plans."""
    from backend.meta.mantic_scaffold import mantic_scaffold_engine
    analysis = mantic_scaffold_engine.analyze_scaffold(
        objective=req.objective,
        custom_layers=req.custom_layers
    )
    return analysis.to_dict()


# 8. CyberScan & Tamper-Proof Audit
class CyberScanRequest(BaseModel):
    code_snippet: Optional[str] = None
    target_directory: Optional[str] = None


@router.post("/security/cyberscan/run")
async def security_cyberscan_run(req: CyberScanRequest):
    """Runs isolated vulnerability scanner for code snippets or workspace directories."""
    from backend.security.cyberscan import cyberscan_agent
    from backend.security.tamper_proof_audit import merkle_audit_ledger

    if req.code_snippet:
        findings = cyberscan_agent.scan_code_snippet(req.code_snippet)
        return {"findings": [f.to_dict() for f in findings], "mode": "snippet"}

    target = req.target_directory or "backend"
    report = cyberscan_agent.run_repository_scan(target)

    merkle_audit_ledger.append_event(
        event_type="CYBERSCAN_AUDIT_COMPLETED",
        actor_id="CYBERSCAN_AGENT",
        payload={"scan_id": report.scan_id, "findings_count": report.findings_count, "compliance_score": report.compliance_score}
    )
    return report.to_dict()


@router.get("/security/audit-ledger")
async def security_audit_ledger():
    """Returns Merkle root, verification integrity status, and recent chained audit blocks."""
    from backend.security.tamper_proof_audit import merkle_audit_ledger
    integrity = merkle_audit_ledger.verify_ledger_integrity()
    blocks = merkle_audit_ledger.get_recent_blocks(15)
    return {
        "integrity": integrity,
        "recent_blocks": blocks
    }

