"""
Sovereign AI Workbench — DOCX Generator

Generate Word documents from AI analysis results.
Supports approval notes, inspection reports, and custom templates.
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger("sovereign.generators.docx")


class DocxGenerator:
    """Generate DOCX documents from structured data."""

    def __init__(self, output_dir: str = "./data/output"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    async def generate_approval_note(
        self,
        title: str,
        inspection_data: dict,
        analysis: str,
        recommendation: str,
        sources: list[dict],
    ) -> str:
        """
        Generate a CSMOP-style approval note from inspection analysis.

        Returns: Path to generated DOCX file
        """
        try:
            from docx import Document
            from docx.shared import Inches, Pt
            from docx.enum.text import WD_ALIGN_PARAGRAPH

            doc = Document()

            # Title
            title_para = doc.add_heading(title, level=0)
            title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

            # Metadata
            doc.add_paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d')}")
            doc.add_paragraph(f"Generated by: Sovereign AI Workbench")
            doc.add_paragraph(f"Classification: INTERNAL")
            doc.add_paragraph("─" * 60)

            # Inspection Summary
            doc.add_heading("Inspection Summary", level=1)
            for key, value in inspection_data.items():
                doc.add_paragraph(f"{key}: {value}")

            # AI Analysis
            doc.add_heading("Analysis", level=1)
            doc.add_paragraph(analysis)

            # Recommendation
            doc.add_heading("Recommendation", level=1)
            doc.add_paragraph(recommendation)

            # Sources
            doc.add_heading("Referenced Documents", level=1)
            for i, source in enumerate(sources, 1):
                doc.add_paragraph(
                    f"[{i}] {source.get('document_id', 'N/A')} — "
                    f"p.{source.get('page', '?')}: {source.get('snippet', '')[:100]}"
                )

            # Save
            filename = f"approval_note_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
            filepath = self.output_dir / filename
            doc.save(str(filepath))
            logger.info("Generated approval note: %s", filepath)
            return str(filepath)

        except ImportError:
            logger.error("python-docx not installed")
            return ""

    async def generate_report(self, title: str, sections: list[dict]) -> str:
        """Generate a generic report DOCX."""
        try:
            from docx import Document

            doc = Document()
            doc.add_heading(title, level=0)
            doc.add_paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d')}")

            for section in sections:
                doc.add_heading(section.get("title", ""), level=section.get("level", 1))
                doc.add_paragraph(section.get("content", ""))

            filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
            filepath = self.output_dir / filename
            doc.save(str(filepath))
            return str(filepath)

        except ImportError:
            return ""


# Global instance
docx_generator = DocxGenerator()
