"""
Sovereign AI Workbench — PPTX Generator

Generate PowerPoint presentations from AI analysis.
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger("sovereign.generators.pptx")


class PptxGenerator:
    """Generate PowerPoint presentations."""

    def __init__(self, output_dir: str = "./data/output"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    async def generate_presentation(self, title: str, slides: list[dict]) -> str:
        """Generate a presentation from structured slide data."""
        try:
            from pptx import Presentation
            from pptx.util import Inches, Pt

            prs = Presentation()

            # Title slide
            slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(slide_layout)
            slide.shapes.title.text = title
            slide.placeholders[1].text = (
                f"Generated by Sovereign AI Workbench\n"
                f"{datetime.now().strftime('%Y-%m-%d')}"
            )

            # Content slides
            for slide_data in slides:
                slide_layout = prs.slide_layouts[1]
                slide = prs.slides.add_slide(slide_layout)
                slide.shapes.title.text = slide_data.get("title", "")

                body = slide.placeholders[1]
                body.text = slide_data.get("content", "")

                # Add bullet points if provided
                for bullet in slide_data.get("bullets", []):
                    p = body.text_frame.add_paragraph()
                    p.text = bullet
                    p.level = 1

            filename = f"presentation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
            filepath = self.output_dir / filename
            prs.save(str(filepath))
            logger.info("Generated PPTX: %s", filepath)
            return str(filepath)

        except ImportError:
            logger.error("python-pptx not installed")
            return ""


# Global instance
pptx_generator = PptxGenerator()
